services:
  cato-monitor:
    container_name: cato-monitor
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    image: cato-monitor
    privileged: true
    restart: unless-stopped    
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    
networks:
  display-network:
    driver: bridge